[tool.poetry]
name = "cmip6"
version = "0.1.0"
description = ""
authors = ["tueboesen <tue.boesen@protonmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
cdsapi = "^0.6.1"



[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
